name: Continuous Integration

on:
  push:
    branches: [ main, trying, staging ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "build: Full build and integrated tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes recursive-nix ca-derivations
      - name: Build
        run: nix build
      - name: Flake check
        run: nix flake check
      - name: Smoke run
        run: curl -s https://cache.nixos.org/z4ddqkq231v5i113wa1kg0ccxgb4s4g7.narinfo | nix run . -- json
